### ISSUE TITLE
how can i change the email? 

### ISSUE THREAD

**Issue by NikoT** [Iterable/iterable-ios-sdk#36]
Because the email is a readonly value.  
If a user log out account(email), and log in another email, how can i register the new email to iterable?

**Comment by dontgitit** [comment]
Hey @NikoT would this address your issue?
https://github.com/Iterable/iterable-ios-sdk#disabling-push-notifications-to-a-device

**Comment by NikoT** [comment]
The disableling method doesn't clear the singleton,  and the only time i can really change the email is at init time. 
i agree with  nmartin867  , add a clear sharedInstance will be good.

**Comment by dontgitit** [comment]
Yep, I agree that we need to add a method to clear a shared instance. In the meantime, you can use the non-static inits to create your own IterableApi, and make a new one when you want to handle a new user logging in.
