### ISSUE TITLE
iOS Xamarin bindings for Iterable

### ISSUE THREAD

**Issue by Jjastiny** [Iterable/iterable-ios-sdk#45]
I've created a binding library for IterableSDK.
Objective C has some method that cannot be converted into C#

This problem was caused by Objective-C letting multiple functions have same parameter types. This binding moves the userId parameter after the NSDictionary launchOptions to avoid that problem.

The binding works perfectly fine, but I was wondering if you guys could take a look at this as well.

https://github.com/Jjastiny/IterableIOSBindings

**Comment by davidtruong** [comment]
Thanks for the note, the bindings look fine for updating the parameters for SharedInstanceWithApiKey. Are you going to be continuing to update the Xamarin binding as we expand on the SDK?

I'll look into updating the sharedInstanceWithApiKey method to not use conflicting data types. I'll get it updated to use sharedInstanceWithApiKeyWithUserId in the future to match what we have on the Android side.

**Comment by Jjastiny** [comment]
Thanks for looking into it. I think I'll continue to update the bindings if we continue to use Iterable. If there is a critical update, then let me know and I'll get on it.
