### ISSUE TITLE
Does `registerToken` automatically retry after failures?

### ISSUE THREAD

**Issue by pepasflo** [Iterable/iterable-ios-sdk#46]
Something which is a bit ambiguous in the [documentation](https://github.com/Iterable/iterable-ios-sdk/blob/master/README.md) is what happens when a call to `registerToken` fails.  Will the Iterable SDK automatically retry to register this token later (e.g. upon regaining reachability or resuming from background), or is it up to the client developer to implement retry upon failure?

**Comment by dontgitit** [comment]
There is no retry logic; if it fails, it fails.

**Comment by pepasflo** [comment]
Thanks!
