### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by ajayjapan** [Iterable/iterable-ios-sdk#5]
Would be nice to have cocoapods support. 

For starters a podspec file would be nice. 
Example: https://github.com/achainan/WebView/blob/master/ACWebViewController.podspec
Details: https://guides.cocoapods.org/syntax/podspec.html

Thanks!

**Comment by dontgitit** [comment]
I've released this as a cocoapod (IterableSDK). Cheers!
