### ISSUE TITLE
Cocoapod missing files?

### ISSUE THREAD

**Issue by tony-boxed** [Iterable/iterable-ios-sdk#67]
I'm trying to install via cocoapods but files seem to be missing. For instance, IterableConfig.h and .m, and many others.

Am I misunderstanding something?

**Comment by vbabenkoru** [comment]
Hi @tony-boxed, thanks for the report.
Please check the version of the Iterable SDK you're checking out. Is it the latest version?

**Comment by tony-boxed** [comment]
Yes, the latest version.

How do I correctly import the library to be used? is it simply #import 'IterableAPI.h' ? When I do this, IterableConfig doesn't register.

**Comment by vbabenkoru** [comment]
Are you using Swift or Objective-C in your app? Do you have `use_frameworks!` in your Podfile?

**Comment by shopped** [comment]
Hi Tony! The cached version when I was installing was 4.7, and the latest PodSpec is 5.0.3. Try running this command

>> pod repo update

Then reinstalling, and maybe even explicitly setting 'IterableSDK', '~> 5.0.3'

**Comment by davidtruong** [comment]
@tony-boxed: Feel reach out to our support directly if you have any additional questions.
